language: java
sudo: true
jdk:
  - oraclejdk8
after_success:
  - echo "TRAVIS_BRANCH='$TRAVIS_BRANCH'";
    echo "JAVA_HOME='$JAVA_HOME'";
    if [ "$TRAVIS_BRANCH" == "master" ]; then
      sbt \
        'set buildSnapshot := true' \
        'set javacOptions in (Compile, doc) ++= Seq("-quiet")' \
        'set test in publish := {}' \
        'set resolvers += Resolver.url("bintray-sbt-plugin-releases", url("http://dl.bintray.com/content/sbt/sbt-plugin-releases"))(Resolver.ivyStylePatterns)' \
        'set publishTo := Option("artifactory-snapshots-publish" at "https://artifactory.broadinstitute.org/artifactory/libs-snapshot-local;build.timestamp=" + new java.util.Date().getTime)' \
        "set credentials += Credentials(\"Artifactory Realm\", \"artifactory.broadinstitute.org\", \"${ARTIFACTORY_USERNAME}\", \"${ARTIFACTORY_PASSWORD}\")" \
        publish;
    fi
